#!/bin/sh

cp hosts.all hosts
./foreachhost ./shape del_delay

cp hosts.region_one hosts
./foreachhost DST_ADDR=10.3.90.2 ./shape add_delay

cp hosts.region_two hosts
./foreachhost DST_ADDR=10.3.89.2 ./shape add_delay
