#!/bin/sh

PROGRAM=$1
CORE=$2
BACKTRACE=gdb.backtrace.${CORE}

rm -f ${BACKTRACE}
GDB_COMMANDS="gdb.commands"

cat <<- __EOF__ >> ${GDB_COMMANDS}
    set logging file ${BACKTRACE}
    set logging on
    set pagination off

    echo \n\n--------------------------------------------------\n\n
    echo SHARED LIBRARIES: \n\n
    info sharedlibrary

    echo \n\n--------------------------------------------------\n\n
    echo REGISTERS: \n\n
    info registers

    echo \n\n--------------------------------------------------\n\n
    echo BACKTRACE: \n\n
    thread apply all bt full
__EOF__

gdb --batch-silent -x ${GDB_COMMANDS} ${PROGRAM} ${CORE}
rm ${GDB_COMMANDS}

